### ISSUE TITLE
Can't require basisjs inside node.js

### ISSUE THREAD

**Issue by istrel** [basisjs/basisjs#53]
In order to play with it in sandbox I want to require it. But I get the message error instead

```
> require('basisjs')
TypeError: Cannot read property 'filename' of undefined
    at processConfig (/Users/ivstrelkov/web-frontend/node_modules/basisjs/src/basis.js:1385:28)
    at fetchConfig (/Users/ivstrelkov/web-frontend/node_modules/basisjs/src/basis.js:1298:12)
    at createBasisInstance (/Users/ivstrelkov/web-frontend/node_modules/basisjs/src/basis.js:1241:16)
    at Object.<anonymous> (/Users/ivstrelkov/web-frontend/node_modules/basisjs/src/basis.js:4060:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
>
```

**Comment by lahmatiy** [comment]
Fixed in [1.10.3](https://github.com/basisjs/basisjs/releases/tag/v1.10.3)
